name: Compile and Publish Executable

on:
  push:
    branches:
      - main  # Replace with your branch if different

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: libs

    - name: Checkout https://github.com/openshwprojects/OpenBK7231T_App
      uses: actions/checkout@v3
      with:
        repository: openshwprojects/OpenBK7231T_App
        path: OpenBK7231T_App
        ref: main

    - name: Copy files from lib to app (excluding examples)
      run: |
        if not exist app mkdir app
        xcopy lib app /E /I /Y /EXCLUDE:libs\exclude.txt

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86
    - name: Build something requiring CL.EXE
      run: |
        cmake -G "NMake Makefiles" .
        nmake