name: Compile and Publish Executable

on:
  push:
    branches:
      - main  # Replace with your branch if different

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: libs

    - name: Checkout https://github.com/openshwprojects/OpenBK7231T_App
      uses: actions/checkout@v3
      with:
        repository: openshwprojects/OpenBK7231T_App
        path: OpenBK7231T_App
        ref: main

    - name: Copy files from lib to app (excluding examples)
      run: |
        dir OpenBK7231T_App
        xcopy libs\* OpenBK7231T_App /E /I /Y /EXCLUDE:libs\exclude.txt
        dir OpenBK7231T_App
        dir

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86
    - name: Build something requiring CL.EXE
      run: |
        cd OpenBK7231T_App
        msbuild openBeken_win32_mvsc2017.vcxproj /p:Configuration=Release
        dir /s /b "*.exe" ||  dir /s /b "C:\*.exe"
